The "7-base_geometry.py" module
================================

Testing "BaseGeometry" class
-----------------------------------

>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry



testing "area()" method
-----------------------------

testing normal condition:
    >>> bg = BaseGeometry()
    >>> try:
    ...     bg.area()
    ... except Exception as e:
    ...     print("[{}] {}".format(e.__class__.__name__, e))
    [Exception] area() is not implemented



testing "integer_validator" method
-----------------------------

testing normal condition:
    >>> bg = BaseGeometry()
    >>> bg.integer_validator("name", 5)
    
testing typeError:
    >>> bg = BaseGeometry()
    >>> try:
    ...     bg.integer_validator("name", "John")
    ... except Exception as e:
    ...     print("[{}] {}".format(e.__class__.__name__, e))
    [TypeError] name must be an integer

testing typeError:
    >>> bg = BaseGeometry()
    >>> try:
    ...     bg.integer_validator("name", None)
    ... except Exception as e:
    ...     print("[{}] {}".format(e.__class__.__name__, e))
    [TypeError] name must be an integer

testing typeError:
    >>> bg = BaseGeometry()
    >>> try:
    ...     bg.integer_validator("name", True)
    ... except Exception as e:
    ...     print("[{}] {}".format(e.__class__.__name__, e))
    [TypeError] name must be an integer

testing typeError:
    >>> bg = BaseGeometry()
    >>> try:
    ...     bg.integer_validator("name", [5, 4])
    ... except Exception as e:
    ...     print("[{}] {}".format(e.__class__.__name__, e))
    [TypeError] name must be an integer

testing typeError:
    >>> bg = BaseGeometry()
    >>> try:
    ...     bg.integer_validator("name", (5, 4))
    ... except Exception as e:
    ...     print("[{}] {}".format(e.__class__.__name__, e))
    [TypeError] name must be an integer

testing valueError:
    >>> bg = BaseGeometry()
    >>> try:
    ...     bg.integer_validator("name", -5)
    ... except Exception as e:
    ...     print("[{}] {}".format(e.__class__.__name__, e))
    [ValueError] name must be greater than 0

